### ISSUE TITLE
Add support for downloading an image of generated cards

### ISSUE THREAD

**Issue by forrestcoward** [forrestcoward/MTG-Card-Generator#2]
Add a way to capture an image of a generated card. The image should include the explanation if the "Explain Yourself" setting was used.

**Comment by marshmellion** [comment]
heya iv been using your site for many months now and was wondering if you still have plans to finish this feature. it would be really nice. hecc perhaps you could go a step further and let us export our my cards area as a .mse (magic set editor) file. this would be amazing. (also let me know if you have a patreon or something a project like this deserves at least some coffee money.

**Comment by forrestcoward** [comment]
Hey Marshmellion, thanks for using the website! This is a feature I can add for you. I'm not familiar with .mse but I can look it up.
Not worries on the donation, this is just a pet project for me for now but I appreciate the thought.

**Comment by marshmellion** [comment]
> Hey Marshmellion, thanks for using the website! This is a feature I can add for you. I'm not familiar with .mse but I can look it up. Not worries on the donation, this is just a pet project for me for now but I appreciate the thought.

That would be really really Awsome. Also cool new hd image feature. This has to be costing you so if you ever need some donations do let me know.

But yeah the magic set editor export would allow for easy playing of the cards using other programs as well as easy sharing and editing of these cards.

Mse is used by a large majority of custom mtg and ai mtg fans/creators. It is open source I think as well. If you need info on creating mse files head over to the robo rosewater ai discord as their devs have clearly done a lot of work with it and are quite likely to share some code with you if you ask or need help.

Their discord is called mtg neural net. The invite should be easy to find in various places like reddit or Twitter or any site that databases discord servers.

The urzas ai discord as now uses your ai as Its main entertainment and a yt VOD or two with cards from your site/urzasai didcord have shown up.

**Comment by forrestcoward** [comment]
Hey @marshmellion, just deployed a new feature that lets you download images of generated cards. I also posted about this in the Urza AI discord, so thanks for the heads up! We can create another ticket for the .mse file download. Thanks for the support!

![image](https://github.com/forrestcoward/MTG-Card-Generator/assets/1037002/1b952f1c-72a3-4859-8982-e45132a70c26)
